//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantastiskGrillApplikation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ingredient()
        {
            this.Tbl_HasIngredient = new HashSet<Tbl_HasIngredient>();
        }
    
        public int In_Id { get; set; }
        public string In_Name { get; set; }
        public string In_Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HasIngredient> Tbl_HasIngredient { get; set; }
    }
}
