//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantastiskGrillApplikation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HasIngredient
    {
        public int HI_Id { get; set; }
        public int HI_Me_Id { get; set; }
        public int HI_In_Id { get; set; }
        public int HI_Quantity { get; set; }
    
        public virtual Tbl_Ingredient Tbl_Ingredient { get; set; }
        public virtual Tbl_Menu Tbl_Menu { get; set; }
    }
}
